In [2]:
star_Li2S8 = -610.8470395
star_Li2S7 = -606.6641962
star_Li2S6 = -602.4350682
star_Li2S5 = -597.162557
star_Li2S4 = -593.5144929
star_Li2S3 = -588.8814615
star_Li2S2 = -584.4246783
star_LiS7 = -602.69573
star_LiS6 = -598.33399
star_LiS5 = -593.74399
star_LiS4 = -589.9442867
star_LiS3 = -585.6063252
star_LiS2 = -580.7525096
star_2LiS = -582.3069372
star_LiS = -576.0138181
S_star = -573.1133418
S2_star = -577.1774164
S3_star = -581.6660657
S4_star = -585.6795208
S5_star = -589.6981242
S6_star = -594.0393055
star_Li2S = -578.2591581
S8_star = -603.2930708
	
Li2S =	-8.05368437
Li2S2 = -13.27015486
Li2S3 = -18.09956187
Li2S4 = -22.78812475
Li2S5 = -27.1625576
Li2S6 = -31.53394194
Li2S7 = -35.67465671
Li2S8 = -39.77130788
S8 = -33.5164502
Li = -2.07696799
two_Li = -4.15393598
MoS2 = -569.75

In [3]:
result_1 = Li2S8+ MoS2 - S8_star - two_Li
result_2 = star_LiS + Li2S7 - Li2S8 - Li- MoS2
result_3 = star_LiS2 + Li2S6 - Li2S8 - Li- MoS2
result_4 = star_LiS3 + Li2S5 - Li2S8 - Li- MoS2
result_5 = star_LiS4 + Li2S4 - Li2S8 - Li- MoS2
result_6 = star_LiS5 + Li2S3 - Li2S8 - Li- MoS2
result_7 = star_LiS6 + Li2S2 - Li2S8 - Li- MoS2
result_8 = star_LiS7 + Li2S + star_Li2S - Li2S - MoS2- Li2S8 - Li - MoS2
result_9 = star_LiS + Li2S6 - Li2S7 - Li - MoS2
result_10 = star_LiS2 + Li2S5 - Li2S7 - Li - MoS2
result_11 = star_LiS3 + Li2S4 - Li2S7 - Li - MoS2
result_12 = star_LiS4 + Li2S3 - Li2S7 - Li - MoS2
result_13 = star_LiS5 + Li2S2 - MoS2 - Li2S7 - Li
result_14 = S8*(1/8)+ MoS2 + Li2S6  - star_LiS7 - Li
result_15 = S8*(2/8)+ MoS2 + Li2S5 - star_LiS7 - Li
result_16 = S8*(3/8)+ MoS2 + Li2S4 - star_LiS7 - Li
result_17 = S8*(4/8)+ MoS2 + Li2S3 - star_LiS7 - Li
result_18 = S8*(5/8)+ MoS2 + Li2S2 - star_LiS7 - Li
result_19 = S8*(6/8)+ MoS2 + Li2S + star_Li2S - MoS2 - Li2S  - star_LiS7 - Li
result_20 = S8*(5/8)+ MoS2 + Li2S + star_Li2S - MoS2 - Li2S  - star_LiS6 - Li
result_21 = S8*(4/8)+ MoS2 + Li2S2 - star_LiS6 - Li
result_22 = S8*(3/8)+ MoS2 + Li2S3 - star_LiS6 - Li
result_23 = S8*(2/8)+ MoS2 + Li2S4 - star_LiS6 - Li
result_24 = S8*(1/8)+ MoS2 + Li2S5 - star_LiS6 - Li
result_25 = star_LiS + Li2S5 - Li2S6 - Li - MoS2
result_26 = star_LiS2 + Li2S4 - Li2S6 - Li - MoS2
result_27 = star_LiS3 + Li2S3 - Li2S6 - Li - MoS2
result_28 = star_LiS4 + Li2S2 - Li2S6 - Li - MoS2
result_29 = star_LiS5 + Li2S + star_Li2S - Li2S - MoS2 - Li2S6 - Li - MoS2 #
result_30 = star_LiS + Li2S4 - Li2S5 - Li - MoS2
result_31 = star_LiS2 + Li2S3 - Li2S5 - Li - MoS2
result_32 = star_LiS3 + Li2S2 - Li2S5 - Li - MoS2
result_33 = star_LiS4 + Li2S + star_Li2S- MoS2 - Li2S - MoS2-Li2S5 - Li #
result_34 = S8*(1/2) + Li2S + MoS2 + star_Li2S - MoS2 - Li2S  - star_LiS5 - Li
result_35 = S8*(3/8)+ MoS2 + Li2S2 - star_LiS5 - Li
result_36 = S8*(2/8)+ MoS2 + Li2S3 - star_LiS5 - Li
result_37 = S8*(1/8)+ MoS2 + Li2S4 - star_LiS5 - Li
result_38 = S8*(3/8) + MoS2 + Li2S + star_Li2S - MoS2 - Li2S  - star_LiS4 - Li
result_39 = S8/4 + MoS2 + Li2S2 - star_LiS4 - Li
result_40 = S8*(1/8)+ MoS2 + Li2S3 - star_LiS4 - Li
result_41 = star_LiS2 + Li2S2 - MoS2 - Li2S4 - Li
result_42 = star_LiS3 + Li2S + star_Li2S - Li2S- MoS2 - MoS2 - Li2S4 - Li #
result_43 = star_LiS + Li2S3 - MoS2 - Li2S4 - Li
result_44 = star_LiS2 + Li2S + star_Li2S - Li2S - MoS2- MoS2-Li2S3 - Li #
result_45 = Li2S + star_LiS + star_Li2S - Li2S - MoS2- Li2S2 - Li - MoS2 #
result_46 = S8*(1/8) + MoS2 + Li2S + star_Li2S - MoS2 - Li2S  - star_LiS2 - Li
result_47 = star_2LiS - star_LiS2 - Li
result_48 = Li2S3 + MoS2 - star_LiS3 - Li
result_49 = S8*(2/8) + Li2S + MoS2 + star_Li2S - MoS2 - Li2S  - star_LiS3 - Li
result_50 = S8*(1/8) + MoS2 + Li2S2 - star_LiS3 - Li
result_51 = Li2S2 + MoS2 - star_LiS2 - Li
result_52 = MoS2 + Li2S2 + Li2S + star_Li2S - MoS2 - Li2S  - star_LiS - Li - Li2S2
result_53 = star_LiS2 - S8*(2/8) - MoS2 - Li
result_54 = star_LiS - S8*(1/8) - MoS2 - Li
result_55 = star_LiS3 - S8*(3/8) - MoS2 - Li
result_56 = star_LiS4 - S8*(1/2) - MoS2 - Li
result_57 = star_LiS5 - S8*(5/8) - MoS2 - Li
result_58 = star_LiS6 - S8*(6/8) - MoS2 - Li
result_59 = Li2S3+ MoS2 - star_LiS3 - Li
result_60 = MoS2+Li2S4 - star_LiS4 - Li
result_61 = MoS2+Li2S5 - star_LiS5 - Li
result_62 = Li2S6 + MoS2 - star_LiS6 - Li
result_63 = Li2S7 + MoS2 - star_LiS7 - Li
result_64 = star_LiS + Li2S + star_Li2S - MoS2 - Li2S - Li - star_2LiS
result_65 = star_Li2S - Li - star_LiS 
result_66 = MoS2+Li2S3 + Li2S + star_Li2S - MoS2 - Li2S  - Li - star_LiS - Li2S3
result_67 = MoS2+Li2S5 + Li2S + star_Li2S - MoS2 - Li2S  - Li - star_LiS - Li2S5
result_68 = MoS2+Li2S4 + Li2S + star_Li2S - MoS2 - Li2S  - Li - star_LiS - Li2S4
result_69 = MoS2+Li2S3 + Li2S2 - Li - star_LiS2 - Li2S3
result_70 = MoS2+Li2S7 + Li2S + star_Li2S - MoS2 - Li2S  - Li - star_LiS - Li2S7
result_71 = MoS2+Li2S6 + Li2S + star_Li2S - MoS2 - Li2S  - Li - star_LiS - Li2S6
result_72 = MoS2+Li2S6 + Li2S2 - Li - star_LiS2 - Li2S6
result_73 = MoS2+Li2S5 + Li2S3- Li - star_LiS3 - Li2S5
result_74 = MoS2+Li2S - star_Li2S
result_75 = MoS2+Li2S5 + Li2S2- Li - star_LiS2 - Li2S5
result_76 = MoS2+Li2S4 + Li2S3- Li - star_LiS3 - Li2S4
result_77 = MoS2+Li2S4 + Li2S2- Li - star_LiS2 - Li2S4

In [3]:
import pandas as pd

data_free_energy = []
data_free_energy.extend([result_1,result_2,result_3,result_4,result_5,result_6,result_7,result_8,result_9,result_10,
            result_11,result_12,result_13,result_14,result_15,result_16,result_17,result_18,result_19,result_20,
            result_21,result_22,result_23,result_24,result_25,result_26,result_27,result_28,result_29,result_30,
            result_31,result_32,result_33,result_34,result_35,result_36,result_37,result_38,result_39,result_40,
            result_41,result_42,result_43,result_44,result_45,result_46,result_47,result_49,result_50,
            result_51,result_52,result_53,result_54,result_55,result_56,result_57,result_58,result_59,result_60,
            result_61,result_62,result_63,result_64,result_65,result_66,result_67,result_68,result_69,result_70,
            result_71,result_72,result_73,result_75,result_76,result_77])
df_free_energy = pd.DataFrame(data_free_energy,columns=['target'])

In [4]:
data = pd.read_csv('node_edge.csv')
data

,Steps,Li*,*Li2S8,*Li2S7,*Li2S6,*Li2S5,*Li2S4,*Li2S3,*Li2S2,*LiS7,...,*LiS,S*,S2*,S3*,S4*,S5*,S6*,*Li2S,S8*,target
0,1,-1,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-1,0
1,2,-1,-1,1,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
2,3,-1,-1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,-1,-1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,-1,-1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,72,-1,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
71,73,-1,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
72,75,-1,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
73,76,-1,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
74,77,-1,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
data['target'] = df_free_energy['target']
data

,Steps,Li*,*Li2S8,*Li2S7,*Li2S6,*Li2S5,*Li2S4,*Li2S3,*Li2S2,*LiS7,...,*LiS,S*,S2*,S3*,S4*,S5*,S6*,*Li2S,S8*,target
0,1,-1,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,-1,-2.074301
1,2,-1,-1,1,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,-0.090199
2,3,-1,-1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.688176
3,4,-1,-1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-1.170607
4,5,-1,-1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,-1.134136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,72,-1,0,0,2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.190677
71,73,-1,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.166269
72,75,-1,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.190677
73,76,-1,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.166269
74,77,-1,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,-0.190677

In [6]:
data.to_csv('Graph_database.csv',index=False)